# Exported from Render on 2024-04-22T21:12:53Z
services:
- type: web
  name: after_school_life
  runtime: ruby
  repo: https://github.com/AfterSchoolLife/after_school_backend
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec puma -C config/puma.rb
version: "1"
